### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by kayrozen** [sdague/mychevy#20] opened 2021-05-06 19:05 UTC
* mychevy version: 2.1.1
* Python version: 3.8
* Operating System: ubuntu

### Description

Just test mychevy cli

### What I Did

```
Paste the command(s) you ran and the output.
mychevy -c config.ini

If there was a crash, please include the traceback here.

Traceback (most recent call last):
  File "/home/kay/.local/lib/python3.8/site-packages/mychevy/mychevy.py", line 309, in get_cars
    _LOGGER.debug("Vehicles: %s", data["data"]["vehicleMap"])
TypeError: 'NoneType' object is not subscriptable


```

**Comment by BabaIsYou** [comment] 2021-07-01 17:52
Same behaviour for me with Python 3.7 ;-/

**Comment by sdague** [comment] 2021-07-06 19:12
This is a duplicate of https://github.com/sdague/mychevy/issues/22 - will consolidate any answers around that one.

**Closed as completed by sdague** 2021-07-06 19:12 UTC
